local cfg = {}

cfg.items = {
	--------------------UTILIDADES-----------------------
	["energetico"] = { "Energético",0.3 },
	["mochila"] = { "Mochila",1.0 },
	["bandagem"] = { "Bandagem",0.7 },
	["ferramenta"] = { "Ferramenta",3.0 },
	["ferro"] = { "Ferro",0.2 },
	["repairkit"] = { "Kit de Reparos",1.0 },
	["militec"] = { "Militec-1",0.8 },
	["alianca"] = { "Aliança",0.0 },
	["roupas"] = { "Roupas",0.01 },
	["etiqueta"] = { "Etiqueta",0.0 },
	["receitamedica"] = { "Receita Médica",0.3 },	
	["remedio"] = { "Remédio",0.7 },
	["identidade"] = {"Identidade",0.0 },
	["cnh"] = {"CNH",0.0 },
	["roupas"] = {"Roupas",0.0 },
	["celular"] = {"Celular IphoneX",0.5 },
	["radio"] = { "Rádio",1.00 },
	["dipirona"] = { "Dipirona",0.7 },
	["dorflex"] = { "Dorflex",0.7 },
	["tarjapreta"] = { "Tarja preta",0.7 },
	--------------------BEBIDAS-----------------------
	["cerveja"] = { "Cerveja",0.7 },
	["tequila"] = { "Tequila",0.7 },
	["vodka"] = { "Vodka",0.7 },
	["whisky"] = { "Whisky",0.7 },
	["conhaque"] = { "Conhaque",0.7 },
	["absinto"] = { "Absinto",0.7 },

	--------------------CARNES-----------------------
	["carnedecormorao"] = { "Carne de Cormorão",0.7 },
	["carnedecorvo"] = { "Carne de Corvo",0.7 },
	["carnedeaguia"] = { "Carne de Águia",0.8 },
	["carnedecervo"] = { "Carne de Cervo",0.9 },
	["carnedecoelho"] = { "Carne de Coelho",0.7 },
	["carnedecoyote"] = { "Carne de Coyote",1 },
	["carnedelobo"] = { "Carne de Lobo",1 },
	["carnedepuma"] = { "Carne de Puma",1.3 },
	["carnedejavali"] = { "Carne de Javali",1.4 },
	["isca"] = { "Isca",0.6 },
	["dourado"] = { "Dourado",0.6 },
	["corvina"] = { "Corvina",0.6 },
	["salmao"] = { "Salmão",0.6 },
	["pacu"] = { "Pacu",0.6 },
	["pintado"] = { "Pintado",0.6 },
	["pirarucu"] = { "Pirarucu",0.6 },
	["tilapia"] = { "Tilápia",0.6 },
	["tucunare"] = { "Tucunaré",0.6 },
	["lambari"] = { "Lambari",0.6 },
	["orgao"] = { "Órgão",1.2 },

	--------------------ITENS FARM LEGAL-----------------------
	["encomenda"] = { "Encomenda",1.5 },
	["trigo"] = { "Trigo",1.0 },
	["sacodelixo"] = { "Saco de Lixo",2.0 },
	["garrafavazia"] = { "Garrafa Vazia",0.2 },
	["malotededinheiro"] = { "Malote de Dinheiro",2.2 },
	["malote"] = { "Malote",1.0 },
	["garrafadeleite"] = { "Garrafa de Leite",0.5 },
	["pizza"] = {"Pizza",0.5 },
	["caixadepizza"] = {"caixadepizza",0.2 },
	["tora"] = { "Tora de Madeira",0.3 },
	["bronze"] = { "Minério de Bronze",1.3 },	
	["prata"] = {"Minério de Prata",1.3 },
	["ouro"] = { "Minério de Ouro",1.3 },	
	["rubi"] = { "Minério de Rubi",1.3 },
	["esmeralda"] = { "Minério de Esmeralda",1.3 },	
	["safira"] = { "Minério de Safira",1.3 },
	["diamante"] = { "Minério de Diamante",1.3 },	
	["topazio"] = { "Minério de Topazio",1.3 },
	["ametista"] = { "Minério de Ametista",1.3 },	
	["bronze2"] = { "Bronze",1.0 },
	["prata2"] = { "Prata",1.0 },	
	["ouro2"] = { "Ouro",1.0 },
	["rubi2"] = { "Rubi",1.0 },
	["esmeralda2"] = { "Esmeralda",1.0 },	
	["safira2"] = { "Safira",1.0 },
	["diamante2"] = { "Diamante",1.0 },	
	["topazio2"] = { "Topazio",1.0 },
	["ametista2"] = { "Ametista",1.0 },		
	["pecamotor"] = { "Peça de Motor",0.3 },	
	["pecatransmissao"] = { "Peça de Transmissão",0.3 },
	["pecafreio"] = { "Peça de Freio",0.3 },	
	["pecaturbo"] = { "Peça de Turbo",0.3 },
	["motor"] = { "Motor",1.0 },	
	["transmissao"] = { "Transmissão",5.0 },
	["freio"] = { "Freio",5.0 },	
	["turbo"] = { "Turbo",5.0 },
	["tinta"] = { "Tinta Automotiva",1.0 },
	["rastreador"] = { "Rastreador de Veículo",5.0 },
	["contratocargo"] = { "Contrato Cargo",1.00 },
	["contatoinformante"] = { "Contato de Informante",1.00 },
	["c4flare"] = { "C4",1.00 },

	--------------------ITENS ILEGAL-----------------------
	["dinheirosujo"] = { "Dinheiro",0.0 },
	["yellowcard"] = { "Yellow",0.3 },
	["algemas"] = { "Algemas",1.0 },
	["kitreparos"] = { "Kit de Reparos",1.0 },
	["capuz"] = { "Capuz",0.5 },
	["placa"] = { "Placa",0.8 },
	["lockpick"] = { "Lockpick",0.3 },
	["masterpick"] = { "Masterpick",0.5 },
	["pendrive"] = { "Pendrive",0.1 },
	["polvora"] = { "Polvora",0.5 },
	["c4"] = { "C4",1.0 },
	["serra"] = { "Serra",2.5 },	
	["furadeira"] = { "Furadeira",1.0 },
	["rubberducky"] = { "Rubberducky",0.1 },
	["colete"] = { "Colete Balístico",5.0 },
	["chavemestra"] = {"Chave Mestra",0.3 },

	--------------------ITENS VENDA ILEGAL-----------------------
	["relogioroubado"] = { "Relógio",0.3 },
	["pulseiraroubada"] = { "Pulseira",0.2 },
	["anelroubado"] = { "Anel",0.2 },
	["colarroubado"] = { "Colar",0.2 },
	["brincoroubado"] = { "Brinco",0.2 },
	["carteiraroubada"] = { "Carteira",0.2 },
	["carregadorroubado"] = { "Carregador",0.2 },
	["tabletroubado"] = { "Tablet",0.2 },
	["sapatosroubado"] = { "Sapatos",0.2 },
	["vibradorroubado"] = { "Vibrador",0.2 },
	["perfumeroubado"] = { "Perfume",0.2 },
	["maquiagemroubada"] = { "Maquiagem",0.2 },
	
	--------------------ITENS FARM ILEGAL-----------------------
	["graos"] = { "Grãos",0.3 },
	["bebidafermentada"] = { "Bebida fermentada",0.8 },
	["moonshine"] = { "Moonshine",0.5 },
	["semente"] = { "Sementes",0.3 },
	["folhadecoca"] = { "Folha De Coca",0.3 },
	["folhadecrack"] = { "Folha De Crack",0.3 },
	["pastadecoca"] = { "Pasta De Coca",0.8 },
	["pastadecrack"] = { "Pasta De Crack",0.8 },
	["crack"] = { "Crack",0.5 },
	["cocaina"] = { "Cocaína",0.5 },
	["adubo"] = { "Adubo",0.3 },
	["fertilizante"] = { "Fertilizante",0.8 },
	["maconha"] = { "Maconha",0.5 },
	["metil"] = { "Metil-1",0.3 },
	["crystalmelamine"] = { "Crystal Melamine",0.8 },
	["metanfetamina"] = { "Metanfetamina",0.5 },
	["capsula"] = { "Cápsula",0.03 },
	["polvora"] = { "Pólvora",0.03 },
	["municao"] = { "Munição",0.09 },
	["componentes"] = { "Componentes",0.09 },
	["pendrivebootavel"] = { "Pendrive Bootavel",0.1 },
	["keylogs"] = { "Keylogs",1.0 },
	["logsinvasao"] = { "Logs Invasao",1.0 },
	["capsuladebala"] = { "Cápsula",0.09 },
	["pecasdearma"] = { "Peças de Armas",0.09 },	
	["pecaspendrive"] = { "Peça de Pendrive",0.09 },
	["cartaoclonado"] = { "Cartao Clonado",1.0 },
	["logsacesso"] = { "Logs de Acesso",0.09 },
	["chavedeacesso"] = { "Chave de Acesso",0.09 },

	--[Evento]--
	["balademorango"] = { "Bala de Morango",0.09 },
	["bengaladoce"] = { "Bengala Doce",0.09 },
	["biscoito"] = { "Biscoito Doce",0.09 },
	["cupcake"] = { "Cupcake de Morango",0.09 },	
	["pirulito"] = { "Pirulito Tutti-frutti",0.09 },
	["carkey"] = { "Car Key",0.09 },
	["overcoin"] = { "Over Coin",0.09 },
	["ceianatalina"] = { "Over Coin",0.09 },
	--[COMIDAS]--
	--[[["chocolate"] = { "Chocolate",1.00 },
	["xtudo"] =  { "x-tudo",1.00 },
    ["pipoca"] = { "Pipoca",1.00 },
    ["taco"] = { "Taco",1.00 },
    ["batatafrita"] = { "Batata Frita",1.00 },
    ["sanduiche"] = { "Sanduiche",1.00 },
	["donut"] = { "Donut",1.00 },
	["churrasco"] = { "Churrasco",1.00 },
    ["hotdog"] = { "Hot Dog",1.00 },
    ["macarrao"] = { "Macarrao",1.00 },
    ["agua"] = { "Agua",1.00 },
    ["fanta"] = { "Fanta",1.00 },
    ["cocacola"] = { "Coca cola",1.00 },
    ["milkshake"] = { "Milkshake",1.00 },
    ["cafe"] = { "Cafe",1.00 },]]
	--[Itens]--
	["adrenalina"] = { "Adrenalina",0.7 },
	["ticketcorrida"] =  { "Race",0.07 },
}

local function load_item_pack(name)
	local items = module("cfg/item/"..name)
	if items then
		for k,v in pairs(items) do
			cfg.items[k] = v
		end
	end
end

load_item_pack("armamentos")

return cfg